id = "deadleaf-theme"
name = "deadleaf theme"
version = "0.0.1"
schema_version = 1
authors = ["Abdelrahman Habib <abdurrahman.habib.dev@proton.me"]
description = "Light and Dark Themes for ZED IDE"
repository = "https://github.com/Abdelrahman-habib/deadleaf-zed-themes"
